[package]
name = "brain-needle"
version = "0.1.0"
edition = "2024"
default-run = "brain-needle"

[dependencies]
ansi_term = "0.12.1"

[dev-dependencies]
criterion = "0.8.2"

[features]
mock-config = []

[lib]
name = "bn"
bench = false

[[bench]]
name = "benches_main"
harness = false

[profile.bench]
debug = true