[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "split-debuginfo=off"]

[alias]
testp = "test -- --nocapture --test-threads=1"
itest = "test --test test*"
itestp = "test --test test* -- --nocapture --test-threads=1"